# https://github.com/realm/SwiftLint
# https://github.com/realm/SwiftLint/blob/master/Rules.md

disabled_rules: # rule identifiers to exclude from running
  - nesting
#included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Generated

line_length: 160 # instead of 120

type_name:
  min_length:
    error: 3 # error instead of warning
  max_length:
    error: 40 # error instead of warning
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
